---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-frontend
  labels:
    name: counter-frontend
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-frontend
  template:
    metadata:
      labels:
        app: counter-frontend
    spec:
      containers:
      - name: counter-frontend
        image: counter-frontend:0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: COUNTER_ENDPOINT
          value: 'http://counter-backend.demo.svc.cluster.local:5000'
        ports:
        - name: frontend-port
          containerPort: 8000
          protocol: TCP
